name: Bedwars
version: 0.1
author: scrouthtv
main: me.scrouthtv.main.Main
api-version: 1.16
depend: [ Multiverse-Core ]
commands:
  give-ingot:
    description: Gives the issuing player a resource ingot.
  build-bedwars:
    description: Creates a new BedWars map for building and teleports the issuing player to it.
  save-bedwars:
    description: Finishes the building of this BedWars map and stores it to the disk.
  load-bedwars:
    description: Loads BedWars maps from the config file.
  list-maps:
    description: Lists all available BedWars maps.
  bw-start:
    description: Creates a new BedWars game from an existing map.
    usage: "Usage: /<command> <map-name> <game-name>"
  bw-join:
    description: Makes this player join a running BedWars game.